name:                engine-jinja-example
version:             0.1.0.0
github:              "datastewardshipwizard/engine-jinja"
license:             Apache-2.0
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@gmail.com"
copyright:           "2025 Marek Suchánek"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/datastewardshipwizard/engine-jinja#readme>

# This refers to libjinja shared library (located in ./lib directory).
# The use of ./lib is specified in the stack.yaml file.
extra-libraries: jinja

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- servant
- servant-server
- vector
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  engine-jinja-example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - engine-jinja-example

tests:
  engine-jinja-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - engine-jinja-example
    - hspec

# It is required to use ForeignFunctionInterface (FFI) to call the C functions
# which are defined in the libjinja shared library.
default-extensions:
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- ForeignFunctionInterface
- OverloadedStrings
- OverloadedRecordDot
