name: Release

on:
  release:
    types: [published]

jobs:
  libs:
    name: Release Libraries

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        os: ['ubuntu-22.04', 'ubuntu-24.04']

    runs-on: ${{ matrix.os }}

    env:
      OUT_NAME: libjinja-python${{ matrix.python-version }}-${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Prepare Python env
      run: |
        python -m pip install -U pip setuptools wheel
        mkdir dist

    - name: Install dependencies
      run: |
        pip install -r ./requirements.txt

    - name: Install Nuitka
      run: |
        pip install Nuitka==2.7.12

    - name: Build library with Nuitka
      run: |
        make lib-python
        ls -lah ./dist

    - name: Build wrapper library
      run: |
        make lib-wrapper
        ls -lah ./dist

    - name: Prepare artifacts
      run: |
        mkdir -p $OUT_NAME
        cp dist/*.so $OUT_NAME/
        ls -lah $OUT_NAME
        tar -czvf $OUT_NAME.tar.gz $OUT_NAME
        ls -lah $OUT_NAME.tar.gz

    - name: Upload release assets
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.OUT_NAME }}.tar.gz
